# Form implementation generated from reading ui file 'd:\PJT\PY\py_PUC_Boxplot\view\ui\Main.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(758, 409)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(Main.sizePolicy().hasHeightForWidth())
        Main.setSizePolicy(sizePolicy)
        self.wxCen = QtWidgets.QWidget(parent=Main)
        self.wxCen.setObjectName("wxCen")
        self.btnMakePlot = QtWidgets.QPushButton(parent=self.wxCen)
        self.btnMakePlot.setGeometry(QtCore.QRect(20, 60, 101, 31))
        self.btnMakePlot.setObjectName("btnMakePlot")
        self.splitter = QtWidgets.QSplitter(parent=self.wxCen)
        self.splitter.setGeometry(QtCore.QRect(170, 95, 581, 222))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter.setObjectName("splitter")
        self.lblMessageHeader = QtWidgets.QLabel(parent=self.splitter)
        self.lblMessageHeader.setMinimumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblMessageHeader.setFont(font)
        self.lblMessageHeader.setObjectName("lblMessageHeader")
        self.txtbrowserMessage = QtWidgets.QTextBrowser(parent=self.splitter)
        self.txtbrowserMessage.setObjectName("txtbrowserMessage")
        Main.setCentralWidget(self.wxCen)
        self.statusbar = QtWidgets.QStatusBar(parent=Main)
        self.statusbar.setObjectName("statusbar")
        Main.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=Main)
        self.toolBar.setMovable(False)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        Main.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.actionShowPlotList = QtGui.QAction(parent=Main)
        self.actionShowPlotList.setObjectName("actionShowPlotList")
        self.actionShowPreferences = QtGui.QAction(parent=Main)
        self.actionShowPreferences.setObjectName("actionShowPreferences")
        self.actionShowAbout = QtGui.QAction(parent=Main)
        self.actionShowAbout.setObjectName("actionShowAbout")

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "MPO To Plot Generator"))
        self.btnMakePlot.setText(_translate("Main", "Make Plot"))
        self.lblMessageHeader.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt; font-weight:700;\">MESSAGE</span></p></body></html>"))
        self.toolBar.setWindowTitle(_translate("Main", "toolBar"))
        self.actionShowPlotList.setText(_translate("Main", "Plot List"))
        self.actionShowPreferences.setText(_translate("Main", "Preferences"))
        self.actionShowAbout.setText(_translate("Main", "About"))
