# Form implementation generated from reading ui file 'c:\PJT\PY\py_PUC_Boxplot\view\ui\Main.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(758, 409)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(Main.sizePolicy().hasHeightForWidth())
        Main.setSizePolicy(sizePolicy)
        self.wxCen = QtWidgets.QWidget(parent=Main)
        self.wxCen.setObjectName("wxCen")
        self.btnMakePlot = QtWidgets.QPushButton(parent=self.wxCen)
        self.btnMakePlot.setGeometry(QtCore.QRect(640, 10, 101, 31))
        self.btnMakePlot.setObjectName("btnMakePlot")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.wxCen)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 130, 741, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.txtbrowserOperationMessage = QtWidgets.QTextBrowser(parent=self.gridLayoutWidget)
        self.txtbrowserOperationMessage.setObjectName("txtbrowserOperationMessage")
        self.gridLayout.addWidget(self.txtbrowserOperationMessage, 1, 2, 1, 1)
        self.textEdit_datasetOrderList = QtWidgets.QTextEdit(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_datasetOrderList.sizePolicy().hasHeightForWidth())
        self.textEdit_datasetOrderList.setSizePolicy(sizePolicy)
        self.textEdit_datasetOrderList.setMinimumSize(QtCore.QSize(100, 200))
        self.textEdit_datasetOrderList.setObjectName("textEdit_datasetOrderList")
        self.gridLayout.addWidget(self.textEdit_datasetOrderList, 1, 0, 1, 1)
        self.lblMessageBoxLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.lblMessageBoxLabel.setMinimumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblMessageBoxLabel.setFont(font)
        self.lblMessageBoxLabel.setObjectName("lblMessageBoxLabel")
        self.gridLayout.addWidget(self.lblMessageBoxLabel, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        Main.setCentralWidget(self.wxCen)
        self.statusbar = QtWidgets.QStatusBar(parent=Main)
        self.statusbar.setObjectName("statusbar")
        Main.setStatusBar(self.statusbar)
        self.actionShowPlotList = QtGui.QAction(parent=Main)
        self.actionShowPlotList.setObjectName("actionShowPlotList")
        self.actionShowPreferences = QtGui.QAction(parent=Main)
        self.actionShowPreferences.setObjectName("actionShowPreferences")
        self.actionShowAbout = QtGui.QAction(parent=Main)
        self.actionShowAbout.setObjectName("actionShowAbout")
        self.actionMakePlot = QtGui.QAction(parent=Main)
        self.actionMakePlot.setMenuRole(QtGui.QAction.MenuRole.ApplicationSpecificRole)
        self.actionMakePlot.setObjectName("actionMakePlot")

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "MPO To Plot Generator"))
        self.btnMakePlot.setText(_translate("Main", "Make Plot"))
        self.lblMessageBoxLabel.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt; font-weight:700;\">MESSAGE</span></p></body></html>"))
        self.actionShowPlotList.setText(_translate("Main", "Plot List"))
        self.actionShowPreferences.setText(_translate("Main", "Preferences"))
        self.actionShowAbout.setText(_translate("Main", "About"))
        self.actionMakePlot.setText(_translate("Main", "MakePlot"))
