# Form implementation generated from reading ui file 'd:\PJT\PY\py_PUC_Boxplot\view\ui\PlotFigure.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PlotFigure(object):
    def setupUi(self, PlotFigure):
        PlotFigure.setObjectName("PlotFigure")
        PlotFigure.resize(1570, 939)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=PlotFigure)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 1551, 871))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layoutMain = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layoutMain.setContentsMargins(0, 0, 0, 0)
        self.layoutMain.setObjectName("layoutMain")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=PlotFigure)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 311, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.layoutCommandButton = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.layoutCommandButton.setContentsMargins(0, 0, 0, 0)
        self.layoutCommandButton.setObjectName("layoutCommandButton")
        self.btnExport_MS_PPT = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.btnExport_MS_PPT.setObjectName("btnExport_MS_PPT")
        self.layoutCommandButton.addWidget(self.btnExport_MS_PPT)
        self.btnExportImage = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.btnExportImage.setObjectName("btnExportImage")
        self.layoutCommandButton.addWidget(self.btnExportImage)

        self.retranslateUi(PlotFigure)
        QtCore.QMetaObject.connectSlotsByName(PlotFigure)

    def retranslateUi(self, PlotFigure):
        _translate = QtCore.QCoreApplication.translate
        PlotFigure.setWindowTitle(_translate("PlotFigure", "Box Plot Graph"))
        self.btnExport_MS_PPT.setText(_translate("PlotFigure", "Export MS PowerPoint"))
        self.btnExportImage.setText(_translate("PlotFigure", "Export Image"))
