# Form implementation generated from reading ui file 'd:\PJT\PY\py_PUC_Boxplot\view\ui\PlotFigure.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frame(object):
    def setupUi(self, frame):
        frame.setObjectName("frame")
        frame.resize(1501, 939)
        self.tabPage = QtWidgets.QTabWidget(parent=frame)
        self.tabPage.setGeometry(QtCore.QRect(10, 50, 1491, 881))
        self.tabPage.setObjectName("tabPage")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabPage.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabPage.addTab(self.tab_2, "")

        self.retranslateUi(frame)
        self.tabPage.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frame)

    def retranslateUi(self, frame):
        _translate = QtCore.QCoreApplication.translate
        frame.setWindowTitle(_translate("frame", "Box Plot Graph"))
        self.tabPage.setTabText(self.tabPage.indexOf(self.tab), _translate("frame", "Tab 1"))
        self.tabPage.setTabText(self.tabPage.indexOf(self.tab_2), _translate("frame", "Tab 2"))
